apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce   # Modo de acceso al volumen (debe coincidir con el PV)
  resources:
    requests:
      storage: 1Gi   # Cantidad de almacenamiento solicitado
