apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx   # Usando una imagen de ejemplo
      volumeMounts:
        - mountPath: "/StoragePV"   # Ruta donde se montará el volumen en el contenedor
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: mongo-pvc   # Nombre del PVC que quieres montar
